### PR TITLE
Updates the toml script to the release tag version; Removes the poetry related config from the toml script; Updates the engine to take checkpoint paths without .safetensors suffix for better user experience.

### PR DESCRIPTION
**Pull request by wang2yn84**
1. Updates the toml script to the release tag version
2. Removes the poetry related config from the toml script
3. Updates the engine to take checkpoint paths without .safetensors suffix for better user experience.

### CODE REVIEW

**Review by FanhaiLu1 — APPROVED** [review]
For 70B, how many safetensors file?

**Comment by FanhaiLu1** [comment]
Can you also update the user guide doc: https://docs.google.com/document/d/1jOzQGZb66VyD1awtW0Vm71BGKGxpUPwIYbX-KVLKOCs/edit?resourcekey=0-LczW5SyjGFCsqaA8o3dr0g&tab=t.0#heading=h.g0e8mz3tgjwb

**Comment by wang2yn84** [comment]
> For 70B, how many safetensors file?

Same thing, there will be 1 safetensors file.

**Comment by wang2yn84** [comment]
> Can you also update the user guide doc: https://docs.google.com/document/d/1jOzQGZb66VyD1awtW0Vm71BGKGxpUPwIYbX-KVLKOCs/edit?resourcekey=0-LczW5SyjGFCsqaA8o3dr0g&tab=t.0#heading=h.g0e8mz3tgjwb

Sure, will be after merged to main.

**Comment by wang2yn84** [comment]
Chatted offline and decided to not update the user guide since JetStream and MaxText are all released with 0.2.0 and let's stick to that for the NEXT release.

**Pull request merged**
