### PR TITLE
Update run_server.py. metrics_server_config is not supported in JetStream[8128c8a] yet

### PR DESCRIPTION
**Pull request by wang2yn84**
[8128c8a](https://github.com/google/JetStream/tree/8128c8a59f859e7691726180b7953e92c6ad4b2b)

### CODE REVIEW

**Review by FanhaiLu1 — COMMENTED** [review]
Can you also update the jetstream to a workable commit?

**Comment by Bslabe123** [comment]
@FanhaiLu1[ Jetstream v0.2.2](https://github.com/google/JetStream/releases/tag/v0.2.2) was just released, possible to bump from 8128c8a59f859e7691726180b7953e92c6ad4b2b -> v0.2.2?

**Review by FanhaiLu1 — COMMENTED** [review]
we can close this PR as the jetstream linked to latest version.

**Comment by wang2yn84** [comment]
Closed. Thank you everyone!

**Pull request closed without merging**
