### PR TITLE
Replace repeat kv with proper GQA handling.

### PR DESCRIPTION
**Pull request by wang2yn84**
Repeat kv in the original llama model will copy the data in some cases. Replace it with reshaping the number of heads dimension in the query to the number of tokens dimension (-2).

### CODE REVIEW

**Review by qihqi — APPROVED** [review]

**Review by FanhaiLu1 — APPROVED** [review]
Smart change! So the q * k^t = [hkv, rep * seq_len, seq_len]  and q * k *v = [hkv, rep * seq_len, d],  you reshape the output to:   [h, seq_len, d] in the end.

**Review by lsy323 — APPROVED** [review]

**Comment by lsy323** [comment]
LGTM! Seems linter needs to be fixed

**Comment by wang2yn84** [comment]
> Smart change! So the q * k^t = [hkv, rep * seq_len, seq_len] and q * k *v = [hkv, rep * seq_len, d], you reshape the output to: [h, seq_len, d] in the end.

Correct. The reshape doesn't affect the result.

**Comment by wang2yn84** [comment]
> LGTM! Thank you for the change. Seems linter needs to be fixed
Yup, fixed!

**Pull request merged**
